### ISSUE TITLE
Add BZGFormField to validation block arguments

### ISSUE THREAD

**Issue by mjjimenez** [0thernet/BZGFormField#12]
Hi again! Just wanted to ask what you think about including the instance of the bzgformfield on the textvalidation block? I think it would be more convenient as opposed to having to use weakSelf to access the bzgformfield inside the validation block.

```
typedef BOOL (^BZGTextValidationBlock)(BZGFormField *field, NSString *text);

//Setting validation block
[self.formField setTextValidationBlock:^BOOL(BZGFormField *field, NSString *text){

//Validate text

//Add error message
field.alterView.title = @"Error Message.";

}];

```

Thanks!

**Comment by 0thernet** [comment]
That seems way more sensible -- if you want to PR, I'll gladly merge.
