### ISSUE TITLE
Unable to add  BZGFormField on UITextField

### ISSUE THREAD

**Issue by mehtatejas** [0thernet/BZGFormField#16]
Hi,
 I am trying to add BZGFormField on UITextField. However, I am getting following errors. Please guide me, how to add BZGFormField on UITextField.

---.h file -----
# import <UIKit/UIKit.h>
# import "BZGFormField.h"

@protocol BZGFormFieldDelegate;

@interface AuthenticationViewController : UIViewController <BZGFormFieldDelegate>

@property(strong,nonatomic) UITextField BZGFormField *emailField;
@property(strong,nonatomic) UITextField *passwordField;
@property(strong,nonatomic) UITextField *passwordConfirmField;

-(void)loadLoginForm;
-(void)loadRegistrationForm;
@end

-----.m -----
# import "AuthenticationViewController.h"
# import "BZGFormField.h"

@interface AuthenticationViewController ()

@end

@implementation AuthenticationViewController
- (void)viewDidLoad
  {
  [super viewDidLoad];
  // Do any additional setup after loading the view.
  [self loadLoginForm];
  }

-(void)loadLoginForm
{
    NSLog(@"AuthenticationViewController loadLoginForm");

```
self.emailField = [[UITextField alloc] initWithFrame:CGRectMake(10, 10, 230, 30)];

self.emailField.text = @"";
self.emailField.placeholder = @"Email";
self.emailField.borderStyle = UITextBorderStyleRoundedRect;
   [self.emailField setTextValidationBlock:^BOOL(BZGFormField *field, NSString *text) {
    // from https://github.com/benmcredmond/DHValidation/blob/master/DHValidation.m
    NSString *emailRegex = @"[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}";
    NSPredicate *emailTest = [NSPredicate predicateWithFormat:@"SELF MATCHES %@", emailRegex];
    if (![emailTest evaluateWithObject:text]) {
        field.alertView.title = @"Invalid email address";
        return NO;
    } else {
        return YES;
    }
}];
self.emailField.delegate = self;
[self.view addSubview:self.emailField];
```

 }

@property(strong,nonatomic) UITextField BZGFormField *emailField;
Error : 
 ---Interface type cannot be statically allocated
 ---Cannot declare variable inside @interface or @protocol

[self.emailField setTextValidationBlock:^BOOL(BZGFormField *field, NSString *text) {
Error:
---No visible @interface for 'UITextField' declares the selector 'setTextValidationBlock:'

**Comment by 0thernet** [comment]
I think you've misunderstood. BZGFormField is a _replacement_ for a UITextField, not something you add to one. Please take a look at the example in `Example`.
