### ISSUE TITLE
Fields can be marked as required

### ISSUE THREAD

**Issue by objectiveSee** [0thernet/BZGFormField#9]
Hi all! I plan to extend this library to support a 'required' boolean. Fields that are required will be marked differently while they are empty. If they have text then normal validation will take place. 

Let me know your thoughts on this! I wil use similar UI to the invalid UI (not sure exactly what it will look like)

thanks!

**Comment by 0thernet** [comment]
Cool, this sounds like a useful addition! Looking forward to the PR!
